### ISSUE TITLE
redirect output to process substitution fails

### ISSUE THREAD

**Issue by dicktyr** [ksh-community/ksh#18]
the following command fails to print the expected output
and writes a file named `$'\312\004'` to the working directory
```
% echo abc > >(cat)
```

expected output
```
% echo abc > >(cat)
abc
```

**Comment by McDutchie** [comment]
This is one of the many bugs already fixed in [ksh 93u+m](https://github.com/ksh93/ksh), see https://github.com/ksh93/ksh/issues/2 and https://github.com/ksh93/ksh/commit/0aa9e03f55f7846c47530d466a7a65d35684cb48.

It doesn't look like the ksh-community project is very active, so please join us at [93u+m](https://github.com/ksh93/ksh) for current development. A beta release is due out in the next few weeks, I'm tying up the loose ends for it now...

**Comment by dicktyr** [comment]
excellent! thank you

please update the other repositories with a link if you can
as I missed it and I imagine others have too

in any case
thank you for maintaining the ksh!

**Comment by McDutchie** [comment]
I'm afraid I have no control over any other repositories, so whether they provide a link is up to them. When the beta is ready I'll of course announce it where I can.

**Comment by dicktyr** [comment]
I added a reference to this repo to [Wikipedia's KornShell article](https://en.wikipedia.org/wiki/KornShell#History)

**Comment by hyenias** [comment]
@dicktyr Can you correct the hyperlink for that Wikipedia KornShell page? When I click on it, I get sent to https://github.com/ksh93/ksh%7Cksh instead of https://github.com/ksh93/ksh.

**Comment by dicktyr** [comment]
actually I just removed the link as per WIkipedia policy
but I left the citation which is correctly linked
